### ISSUE TITLE
Requests version needs to be 2.5.0 or greater from this repo

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-icontrol-rest-python#101]
If a user is starting with a lower version of requests than 2.5.0, they will see failures coming from this module (when attempting to disable the warning messages). We need to set the requests version >= 2.5.0. Otherwise folks get an error:

```
        if StrictVersion(requests_version) < '2.9.1':
            requests.packages.urllib3.disable_warnings()

        AttributeError: 'module' object has no attribute 'packages'
```

**Comment by caphrim007** [comment]
this appears to have been done

https://github.com/F5Networks/f5-icontrol-rest-python/blob/1.0/setup.py#L31
