### ISSUE TITLE
How to configure connection timeout and max retry count?

### ISSUE THREAD

**Issue by edarzins** [F5Networks/f5-icontrol-rest-python#107]
While testing connection-timeout behavior with the BigIP class, I noticed that I receive the following exception after 75 seconds:

HTTPSConnectionPool(host='10.128.1.144', port=443): Max retries exceeded with url: /mgmt/tm/ltm/pool/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x106064ad0>: Failed to establish a new connection: [Errno 60] Operation timed out',))

I would like to be able to configure the timeout and max retry count, but I don't see a way to do that.

**Comment by jasonrahm** [comment]
Hi @edarzins, I know this is super old...are you trying to configure the requests module on the python side for connection timeout and max retry, or manipulate the rest interface itself?

**Comment by f5-rahm** [comment]
archiving this repo, this request will not be implemented.
