### ISSUE TITLE
Setting timeout has no effect

### ISSUE THREAD

**Issue by jpillora** [F5Networks/f5-icontrol-rest-python#132]
iControl attempts to set session timeouts [here](https://github.com/F5Networks/f5-icontrol-rest-python/blob/1.0/icontrol/session.py#L364), however requests Session has no `timeout` attribute, instead it must be passed as a kwarg to `get()`(`request()`) as seen [here](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L426)

**Comment by ghost** [comment]
I see the same behavior. The value needs to be sent as an argument in the operation per http://docs.python-requests.org/en/master/user/advanced/

**Comment by ghost** [comment]
It appears that this line: https://github.com/F5Networks/f5-icontrol-rest-python/blob/1.0/icontrol/session.py#L415 has been deprecated.

**Comment by f5-rahm** [comment]
archiving this repo, this request will not be implemented.
