### ISSUE TITLE
SIX - EL7 depedency

### ISSUE THREAD

**Issue by eperdeme** [F5Networks/f5-icontrol-rest-python#151]
Hello,

Should the dependancy not be python-six for this package ?

yum install -y https://github.com/F5Networks/f5-icontrol-rest-python/releases/download/v1.3.6/f5-icontrol-rest-1.3.6-1.el7.noarch.rpm 
f5-icontrol-rest-1.3.6-1.el7.noarch.rpm                                                                                                                                                                                       |  21 kB  00:00:00     
Examining /var/tmp/yum-root-aLxX2E/f5-icontrol-rest-1.3.6-1.el7.noarch.rpm: f5-icontrol-rest-1.3.6-1.noarch
Marking /var/tmp/yum-root-aLxX2E/f5-icontrol-rest-1.3.6-1.el7.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package f5-icontrol-rest.noarch 0:1.3.6-1 will be installed
--> Processing Dependency: python-requests >= 2.5.0 for package: f5-icontrol-rest-1.3.6-1.noarch
--> Processing Dependency: six<2.0.0 for package: f5-icontrol-rest-1.3.6-1.noarch
--> Processing Dependency: six>=1.9.0 for package: f5-icontrol-rest-1.3.6-1.noarch
--> Running transaction check
---> Package f5-icontrol-rest.noarch 0:1.3.6-1 will be installed
--> Processing Dependency: six<2.0.0 for package: f5-icontrol-rest-1.3.6-1.noarch
--> Processing Dependency: six>=1.9.0 for package: f5-icontrol-rest-1.3.6-1.noarch
---> Package python-requests.noarch 0:2.6.0-1.el7_1 will be installed
--> Finished Dependency Resolution
Error: Package: f5-icontrol-rest-1.3.6-1.noarch (/f5-icontrol-rest-1.3.6-1.el7.noarch)
           Requires: six<2.0.0
Error: Package: f5-icontrol-rest-1.3.6-1.noarch (/f5-icontrol-rest-1.3.6-1.el7.noarch)
           Requires: six>=1.9.0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by cohoe** [comment]
👍 Just spent the better part of an hour beating my brain out thinking my build system was doing something weird.

**Comment by cohoe** [comment]
LGTM. Thanks!
