### ISSUE TITLE
Clean up RPM construction to handle missing SRC_DIR and other fixes

### ISSUE THREAD

**Issue by nkadel** [F5Networks/f5-icontrol-rest-python#159]
The "build-rpms.sh" script can and should be made available to worrk without Docker, and without arguments. It should also deduce the "dist" option from "rpm --showmacros" in the working environment, rather than simply renaming RPMS after compilition to a hardcoded value that does not actually match the rpm name as reported by "rpm -qi".

Naming RPM files this way is something that Sun used to do with Java packages, for no good reason, and it was very confusing.

**Comment by f5-rahm** [comment]
archiving this repo, this request will not be implemented.
