### ISSUE TITLE
passing token to CRUD operations in iControlRestSession

### ISSUE THREAD

**Issue by mirzawaqasahmed** [F5Networks/f5-icontrol-rest-python#171]
Hi ,
I am trying to find a way to pass token to iControlRestSession.
I know we can use token authentication using 'token=true' in iControlRestSession. i.e.
`icr_session = iControlRESTSession(username, password, token=True)`
However, I am more interested in passing the token in future CRUD operation using the iControlRestSession. e.g.
`icr_session.get()` etc

Am I missing something or this isnt possible?

Thanks in advance.

**Comment by f5-rahm** [comment]
archiving this repo, this request will not be implemented.
