### ISSUE TITLE
Enable Proxies for Token Acquisition in `iControlRESTTokenAuth`

### ISSUE THREAD

**Issue by lykinsbd** [F5Networks/f5-icontrol-rest-python#172]
As of #169 "Allow proxies kwarg from sdk ManagementRoot", the `proxies` attribute is pushed all the way down into the `iControlRESTSession` object and [applied to the underlying `requests.Session` object](https://github.com/F5Networks/f5-icontrol-rest-python/blob/1.0/icontrol/session.py#L427).

However, there remains a problem with token acquisition in `iControlRESTTokenAuth` as it appears to still utilize plain `requests.<verb>` calls and does not have access to the outer session or it's proxy configuration.

Example in `iControlRESTTokenAuth.get_new_token()`:
https://github.com/F5Networks/f5-icontrol-rest-python/blob/1.0/icontrol/authtoken.py#L146

Example in `iControlRESTTokenAuth.get_auth_providers()`:
https://github.com/F5Networks/f5-icontrol-rest-python/blob/1.0/icontrol/authtoken.py#L98

This results in a condition where a user is unable to actually utilize the outer proxy-enabled session object, because the acquisition of a token is not proxy-enabled.

---

In my testing, simply passing the `proxies` dict down into `iControlRESTTokenAuth` upon initialization, and then further passing it to the above example `Requests` calls as an additional attribute on the request itself seems to work.

I am happy to open a PR with an attempted fix, just wanted to raise the issue first.

**Comment by mr-grj** [comment]
Any idea when this pull request will be approved and merged into master? I'd really like to use this withing the library and avoid monkeypatching it by myself :)

**Comment by lykinsbd** [comment]
This PR was merged into the current prod branch of “1.0”, and a release was done on Github.  However, it was not pushed/published to Pypi.  I opened https://github.com/F5Networks/f5-icontrol-rest-python/issues/174 to try and get that portion done.

**Comment by mr-grj** [comment]
@lykinsbd awesome! I'm waiting for some good news then! Thanks a lot
