### ISSUE TITLE
Please release v1.3.14 on PyPi

### ISSUE THREAD

**Issue by lykinsbd** [F5Networks/f5-icontrol-rest-python#174]
Hello,

v1.3.14 is built/tagged in the repo, but is not on PyPi: https://pypi.org/project/f5-icontrol-rest/

Please can you make a build/release to PyPi?  As a workaround today, I'm installing directly from the branch on github:

`pip install git+https://github.com/F5Networks/f5-icontrol-rest-python.git/tag/v1.3.14`

And with this in my setup.cfg:

`f5-icontrol-rest-python @ https://github.com/F5Networks/f5-icontrol-rest-python/archive/v1.3.14.tar.gz`

However, ideally I don't want to release my downstream project with that hack/workaround in place, and would much rather go back to a simple:

`f5-icontrol-rest-python>=1.3.14`

Thanks!

**Comment by lykinsbd** [comment]
Forgot to tag @jasonrahm 

Thanks again!

**Comment by lykinsbd** [comment]
@jasonrahm I found that with the "direct link" workaround I listed above in place, downstream projects are unable to be published to PyPi.  Let me know if there's anything I can do to help get v1.3.14 published on PyPi.

**Comment by f5-rahm** [comment]
archiving this repo, this request will not be implemented.
