### ISSUE TITLE
README: update 'Contact' email address 

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-icontrol-rest-python#45]
The email address listed in README and CONTRIBUTING should be changed to f5_icontrol_rest@f5.com.

**Comment by zancas** [comment]
Is this issue still open?

**Comment by jputrino** [comment]
Nope. Fix has been made.

-- Jodie Putrino

On Mar 16, 2016, at 3:49 PM, Za Wilgustus <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this issue still open?

-
