### ISSUE TITLE
Supported f5-icontrol-[rest or wsdl]-ruby release

### ISSUE THREAD

**Issue by hh** [F5Networks/f5-icontrol-rest-python#68]
The wsdl based https://devcentral.f5.com/d/icontrol-ruby-library was never released to rubygems (nor released outside of a manually installed .gem).

I imported it into github so I could look into getting it updated and created a few issues: https://github.com/hh/f5-icontrol/issues/

Are there any plans to release a ruby gem for f5-icontrol-rest?
If not, can we get a supported release of f5-icontrol{-wsdl} pushed to rubygems?

Cheers,
@hh

**Comment by swormke** [comment]
Hi @hh my team only works on the OpenStack (and therefore Python) related packages.  I'll reach out to the folks in F5 that are working on other SDKs and see if I can get an answer for you.

**Comment by hh** [comment]
Thanks @swormke !

**Comment by hh** [comment]
We have a production Openstack install at Rackspace (Private Cloud) behind a pair of BigIps. I'd also be interested to see where we are with being able to modify the F5 via the Openstack API.

**Comment by hh** [comment]
Mainly wanting to use any API from ruby to be able to add/remove members from the pools on the fly.

**Comment by swormke** [comment]
Yep, I think you want the ruby equivalent to https://github.com/F5Networks/f5-common-python right?

**Comment by hh** [comment]
Yeah, we need a supported Ruby SDK for Fog (library), Chef, and Puppet to integrate well with F5.

**Comment by swormke** [comment]
@hh with openstack we have a few options for you.  You can use LBaaS or Heat.  We have [F5 Heat plugins](https://github.com/F5Networks/f5-openstack-heat-plugins) that work similar to what you are asking for puppet/chef and are working on producing some heat templates to get customers started.

**Comment by hh** [comment]
We are using chef-provisioning, so I'm guessing LBaaS calls made from the provisioning node. Is there an integration between the F5 and Openstack LBaaS?

**Comment by swormke** [comment]
Good question, what happens is that the OpenStack community defines the LBaaS API and then third party vendors like F5 implement that API.  The way ours works is that you install a driver into OpenStack and then run an Agent on a machine in your openstack cloud with takes the OpenStack RPC calls and turns them into F5 configuration and applies them to the F5 Device(s).  There is a good overview here: http://f5-openstack-lbaasv1.readthedocs.org/en/1.0/f5-oslbaasv1-readme.html

**Comment by hh** [comment]
Looks like Rackspace hasn't yet incorporated v1, but is looking at v2. Still in the works. Looks like https://github.com/hh/f5-icontrol/issues/3 is getting some traction with the creation of https://github.com/f5networks/f5-icontrol-library-ruby so I'm going to close this. Thanks for giving us some visibility @swormke !
