### ISSUE TITLE
Logging needs to be upgraded

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-icontrol-rest-python#71]
DoD:

Logs are written to a standard location in an os agnostic way.
Few fds are open at any one time.
Performance isn't significantly reduced.
Logging is openstack compatible
The conditions are tested.

**Comment by zancas** [comment]
Extra Condition:

tests show that the first 3 conditions are met.

**Comment by zancas** [comment]
From @pjbreaux:

 '''If you would like to store them in Openstack, and Swift is running in your Openstack cluster, you could store it there. http://docs.openstack.org/developer/swift/api/object_api_v1_overview.html'''

**Comment by pjbreaux** [comment]
Also, the user should be able to set a logging level.
